name: NexusMods Publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Github Release Asset
        id: fetch-release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: 'Race.Interactions.zip'
          target: 'Race.Interactions.zip'

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.x

      - name: Install NexusUploader
        run: dotnet tool install -g NexusUploader;
        shell: pwsh

      - run: |
          unex upload 11 "Race.Interactions.zip" -v "${{ steps.fetch-release.outputs.version }}" ;
          unex changelog "${{ steps.fetch-release.outputs.version }}" "${{ steps.fetch-release.outputs.body }}"
        env:
          UNEX_GAME: songsofsyx
          UNEX_MODID: 11
          UNEX_FILENAME: 'Race Interactions'
          UNEX_FILEDESCRIPTION: ${{ steps.fetch-release.outputs.body }}
          UNEX_PREVIOUSFILE: auto
          UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
          UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
          UNEX_DEBUG: true
        shell: pwsh