name: Release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Create Draft Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "temp-version"
          release_name: "draft-release"
          body: ""
          draft: true
          prerelease: false

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          server-id: github
          server-username: REPOSITORY_USERNAME_REF
          server-password: REPOSITORY_TOKEN_REF

      - name: Package
        env:
          REPOSITORY_USERNAME_REF: ${{ vars.USERNAME }}
          REPOSITORY_TOKEN_REF: ${{ secrets.PERSONAL_TOKEN }}
        run: mvn -B -P github clean package

      - name: Zip
        run: zip Race_Interactions "target/out/Race Interactions"

      - name: Upload zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: "Race_Interactions.zip"
          asset_name: "Race.Interactions.zip"
          asset_content_type: application/octet-stream
