name: Steam Publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Github Release Asset
        id: fetch-release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: 'Race.Interactions.zip'
          target: 'Race.Interactions.zip'

      - name: Unzip
        run: unzip Race.Interactions.zip

      - uses: arma-actions/workshop-upload@v1.0.2
        with:
          appId: '1162750'
          itemId: '2937853965'
          contentPath: 'Race Interactions'
          changelog: ${{ steps.fetch-release.outputs.body }}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_2FASEED: ${{ secrets.STEAM_2FASEED }}
