name: Steam Publish
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: 'Race.Interactions.zip'
          target: 'Race.Interactions.zip'

      - name: Unzip
        run: unzip Race.Interactions.zip

      - name: Echo
        run: ls -la
