name: Steam Publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Github Release Asset
        id: fetch-release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: 'Race.Interactions.zip'
          target: 'Race.Interactions.zip'

      - name: Unzip
        run: unzip Race.Interactions.zip

      - uses: Weilbyte/steam-workshop-upload@v1.1
        with:
          appid: '1162750'
          itemid: '2937853965'
          path: 'Race Interactions'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_TFASEED: ${{ secrets.STEAM_2FASEED }}
