name: Steam Publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Github Release Asset
        id: fetch-release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: 'Race.Interactions.zip'
          target: 'Race.Interactions.zip'

      - name: Unzip
        run: unzip Race.Interactions.zip

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1.1.5

      - name: Generate auth code
        id: generate
        uses: CyberAndrii/steam-totp@v1.0.3
        with:
          shared_secret: ${{ secrets.STEAM_2FASEED }}

      - name: Create vdf file
        run: |
          cat << EOT > ${{ github.workspace }}/workshop_build.vdf
          "workshopitem"
          {
              "appid" "1162750"
              "publishedfileid" "2937853965"
              "contentfolder" "${{ github.workspace }}/Race Interactions/"
              "changenote" "${{ steps.fetch-release.outputs.body }}"
          }
          EOT
          
      - name: Debug
        run: ls -la ${{ github.workspace }} && ls -la "${{ github.workspace }}/Race Interactions" && cat ${{ github.workspace }}/workshop_build.vdf
          
      - name: Steam Publish
        run: steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} ${{ steps.generate.outputs.code }} +workshop_build_item "${{ github.workspace }}/workshop_build.vdf" +quit
